project:
  type: book

book:
  title: "Design and analysis of experiments (R notes)"
  subtitle: "STAT 351"
  author: "Arvind Krishna"
  date: "3/30/2024"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Rintro.qmd
    - t_test_example.qmd
  appendices: 
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo

freeze:
    auto

